Predict error file = D:\Dataset_and_Demo\SETP_GL\2020-02-25_to_2020-05-31\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-5-f311317e6612>", line 54, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2020-05-31_to_2020-09-15\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-5-f311317e6612>", line 54, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2020-09-15_to_2020-11-28\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-5-f311317e6612>", line 54, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2019-02-25_to_2019-05-31\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-1-e8fa7675ee40>", line 66, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2015-02-25_to_2015-05-31\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2015-05-31_to_2015-09-15\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2015-09-15_to_2015-11-28\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2015-11-28_to_2016-02-25\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2016-02-25_to_2016-05-31\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2016-05-31_to_2016-09-15\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2016-09-15_to_2016-11-28\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2016-11-28_to_2017-02-25\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2017-02-25_to_2017-05-31\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2017-05-31_to_2017-09-15\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2017-09-15_to_2017-11-28\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2017-11-28_to_2018-02-25\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2018-02-25_to_2018-05-31\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2018-05-31_to_2018-09-15\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2018-09-15_to_2018-11-28\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2018-11-28_to_2019-02-25\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2019-02-25_to_2019-05-31\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2019-05-31_to_2019-09-15\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2019-09-15_to_2019-11-28\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2019-11-28_to_2020-02-25\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2020-02-25_to_2020-05-31\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2020-05-31_to_2020-09-15\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2020-09-15_to_2020-11-28\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2020-11-28_to_2021-02-25\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2021-02-25_to_2021-05-31\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2021-05-31_to_2021-09-15\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2021-09-15_to_2021-11-28\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2021-11-28_to_2022-02-25\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2022-02-25_to_2022-05-31\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2022-05-31_to_2022-09-15\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2022-09-15_to_2022-11-28\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2022-11-28_to_2023-02-25\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2023-02-25_to_2023-05-31\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2023-05-31_to_2023-09-15\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2023-09-15_to_2023-11-28\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2023-11-28_to_2024-02-25\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2024-02-25_to_2024-05-31\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2024-05-31_to_2024-09-15\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\SETP_GL\2024-09-15_to_2024-11-28\10006_Trans.tif
Traceback (most recent call last):
  File "<ipython-input-10-df42cf664f9a>", line 30, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Wrz\anaconda\envs\samgeo\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

